export const MOTHER_TONGUE_LANGUAGES = [
  { value: 'Assamese', text: 'অসমীয়া' },
  { value: 'Bengali', text: 'বাংলা' },
  { value: 'Bodo', text: 'बोड़ो' },
  { value: 'Dogri', text: 'डोगरी' },
  { value: 'Gujarati', text: 'ગુજરાતી' },
  { value: 'Hindi', text: 'हिंदी' },
  { value: 'Kannada', text: 'ಕನ್ನಡ' },
  { value: 'Kashmiri', text: 'كأشُر' },
  { value: 'Konkani', text: 'कोंकणी' },
  { value: 'Maithili', text: 'मैथिली' },
  { value: 'Malayalam', text: 'മലയാളം' },
  { value: 'Manipuri', text: 'মনিপুরি' },
  { value: 'Marathi', text: 'मराठी' },
  { value: 'Nepali', text: 'नेपाली' },
  { value: 'Odia', text: 'ଓଡିଆ' },
  { value: 'Punjabi', text: 'ਪੰਜਾਬੀ' },
  { value: 'Santali', text: 'ᱥᱟᱱᱛᱟᱞᱤ' },
  { value: 'Sanskrit', text: 'संस्कृतम्' },
  { value: 'Sindhi', text: 'सिंधी' },
  { value: 'Tamil', text: 'தமிழ்' },
  { value: 'Telugu', text: 'తెలుగు' },
  { value: 'Urdu', text: 'اردو' },
] as const;
