const initiativeBaseRoute: { [key: string]: string } = {
  sunoIndia: '/sunoIndia',
  boloIndia: '/boloIndia',
  likhoIndia: '/likhoIndia',
  dekhoIndia: '/dekhoIndia',
} as const;

const routePaths: { [key: string]: string } = {
  root: '/',
  home: '/home',
  sunoIndiaHome: `${initiativeBaseRoute.sunoIndia}/home`,
  sunoIndiaContributeThankYou: `${initiativeBaseRoute.sunoIndia}/thank-you`,
  sunoIndiaValidateThankYou: `${initiativeBaseRoute.sunoIndia}/validator-thank-you`,
  sunoIndiaContribute: `${initiativeBaseRoute.sunoIndia}/record`,
  sunoIndiaValidate: `${initiativeBaseRoute.sunoIndia}/validator-page`,
  sunoIndiaDashboard: `${initiativeBaseRoute.sunoIndia}/dashboard`,
  boloIndiaHome: `${initiativeBaseRoute.boloIndia}/home`,
  boloIndiaContribute: `${initiativeBaseRoute.boloIndia}/record.html`,
  boloIndiaValidate: `${initiativeBaseRoute.boloIndia}/validator-page.html`,
  boloIndiaDashboard: `${initiativeBaseRoute.boloIndia}/dashboard.html`,
  boloIndiaContributeThankYou: `${initiativeBaseRoute.boloIndia}/thank-you`,
  boloIndiaValidateThankYou: `${initiativeBaseRoute.boloIndia}/thank-you-validator`,
  dekhoIndiaHome: `${initiativeBaseRoute.dekhoIndia}/home`,
  dekhoIndiaContribute: `${initiativeBaseRoute.dekhoIndia}/record.html`,
  dekhoIndiaValidate: `${initiativeBaseRoute.dekhoIndia}/validator-page.html`,
  dekhoIndiaDashboard: `${initiativeBaseRoute.dekhoIndia}/dashboard.html`,
  dekhoIndiaContributeThankYou: `${initiativeBaseRoute.dekhoIndia}/thank-you`,
  dekhoIndiaValidateThankYou: `${initiativeBaseRoute.dekhoIndia}/thank-you-validator`,
  likhoIndiaHome: `${initiativeBaseRoute.likhoIndia}/home`,
  likhoIndiaContribute: `${initiativeBaseRoute.likhoIndia}/record.html`,
  likhoIndiaValidate: `${initiativeBaseRoute.likhoIndia}/validator-page.html`,
  likhoIndiaDashboard: `${initiativeBaseRoute.likhoIndia}/dashboard.html`,
  likhoIndiaContributeThankYou: `${initiativeBaseRoute.likhoIndia}/thank-you`,
  likhoIndiaValidateThankYou: `${initiativeBaseRoute.likhoIndia}/thank-you-validator`,
  badges: '/badges.html',
  myBadges: '/my-badges',
  termsAndConditions: '/terms-and-conditions.html',
  privacyPolicy: '/terms-and-conditions.html#privacy-policy',
} as const;

export default routePaths;
