FROM postgres:latest

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl
RUN apt-get install -y unzip
RUN apt-get install -y sudo


WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app/tb_files
COPY db_queries.sql .
COPY db_refresh.sql .
COPY db-refresher.sh .
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN sudo ./aws/install

ENTRYPOINT [ "sh","db-refresher.sh"]
