FROM postgres:latest

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl
RUN apt-get install -y unzip
RUN apt-get install -y sudo
RUN apt-get install -y wget
RUN apt install keyutils
RUN apt-get install -y python3 python3-pip

WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app/tb_files

COPY db_queries.sql .
COPY db_refresh.sql .
COPY db-refresher.sh .

RUN mkdir -p /usr/src/app/utils
RUN wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1

RUN cp azcopy /usr/src/app/utils/

ENTRYPOINT [ "sh","db-refresher.sh"]
