runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  DB_HOST: /cloudsql/<%= ENV['DB_HOST'] %>
  DB_USER: <%= ENV['DB_USER'] %>
  DB_NAME: <%= ENV['DB_NAME'] %>
  DB_PASS: <%= ENV['DB_PASS'] %>
  BUCKET_NAME: <%= ENV['BUCKET_NAME'] %>
  ENCRYPTION_KEY: <%= ENV['ENCRYPTION_KEY'] %>

beta_settings:
  cloud_sql_instances: <%= ENV['DB_HOST'] %>
