version: 2.1
commands:
    delete_files:
        steps:
            - run: rm ${HOME}/gcp-key.json
            - run: rm app.yaml
    create_yaml:
        parameters:
            file:
                type: string
        steps:
            - run:
                command: |
                    chmod +rwx << parameters.file >>
                    ./<< parameters.file >> > app.yaml
jobs:
    build_test:
        docker:
            - image: circleci/node:13.4
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: Tests
                command: npm test
    deploy:
        parameters:
            env_name:
                type: string
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - run:
                name: Authorize gcloud
                command: |
                  echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
                  gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
                  gcloud --quiet config set project ${GCP_PROJECT}
            - run: cd ~/project
            - create_yaml:
                file: app_yaml_test.sh
            - run: gcloud app deploy app.yaml -v test --no-promote
            - delete_files
    approve_for_prod_deploy:
        docker: 
            - image: circleci/node:13.4
        steps:
            - run: echo "Hold for approval"

workflows:
    build_test_deploy:
        jobs:
          - build_test
          - deploy:
                name: deploy_test
                env_name: test
                requires:
                  - build_test
          - approve_for_prod_deploy:
                type: approval
                requires:
                  - deploy_test
          - deploy:
                name: deploy_prod
                env_name: prod
                requires:
                  - approve_for_prod_deploy