version: 2
jobs:
    build_test:
        docker:
            - image: circleci/node:13.4
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: Tests
                command: npm test
    deploy:
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - run: 
                name: Make app.yaml file
                command: |
                  chmod +rwx app_yaml.sh
                  ./app_yaml.sh > app.yaml
            - run:
                name: Authorize gcloud
                command: |
                  echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
                  gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
                  gcloud --quiet config set project ${GCP_PROJECT}
            - deploy:
                name: Deploy app to GAE
                command: |
                  cd ~/project
                  gcloud app deploy app.yaml
                  rm ${HOME}/gcp-key.json
                  rm app.yaml

workflows:
    build_test_deploy:
        jobs:
          - build_test