version: 2
jobs:
    build:
        docker:
            - image: circleci/node:13.4
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
            - run:
                name: install gcloud
                command: |
                  cd ${HOME}
                  wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-265.0.0-linux-x86_64.tar.gz
                  tar -zxf google-cloud-sdk-*
                  cd google-cloud-sdk
                  pwd
                  echo "Installing GCLOUD"
                  ./install.sh --quiet
                  echo "Installed GCLOUD"
                  
                  echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
                  
                  source /home/circleci/google-cloud-sdk/completion.bash.inc
                  source /home/circleci/google-cloud-sdk/path.bash.inc
                  gcloud -v
                  cd {HOME}
                  gcloud components update
            - run:
                name: Deploy in test env
                command: |
                  cd ${HOME}
                  gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
                  gcloud --quiet config set project ${GCP_PROJECT}
                  cd ~/crowdsource-dataplatform
                  gcloud app deploy app.yaml

                  rm ${HOME}/gcp-key.json