version: 2.1
orbs:
  node: circleci/node@4.4.0
  aws-ecr: circleci/aws-ecr@6.15.3
  azure-aks: circleci/azure-aks@0.3.0

  aws-cli: circleci/aws-cli@1.4.0
  kubernetes: circleci/kubernetes@0.11.2
  aws-s3: circleci/aws-s3@2.0.0
  azure-acr: circleci/azure-acr@0.2.0

definition:
  fast-checkout: &fast-checkout
    attach_workspace:
      at: .

jobs:
  create-workspace:
    executor: node/default
    steps:
      - checkout
      - run: rm -rf .git
      - persist_to_workspace:
          root: .
          paths:
            - .

  run_functional_tests:
    parameters:
      env_name:
        type: string
      db_name:
        type: string
    executor:
      name: node/default
    steps:
      - *fast-checkout
      - run:
          name: Gauge tests
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client git-all gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libgbm-dev libappindicator1 libnss3 lsb-release xdg-utils wget
            psql "postgresql://${DEV_DB_USER}:${DB_PASS_AWS}@${DB_HOST_AWS}/<< parameters.db_name >>" -f functional_tests/sql/dataSeed.sql
            sudo rm -rf /var/lib/apt/lists/*
            npm run install:ft
            npm run functional_test -- -- --env <<parameters.env_name>>
            psql "postgresql://${DEV_DB_USER}:${DB_PASS_AWS}@${DB_HOST_AWS}/<< parameters.db_name >>" -f functional_tests/sql/deleteSeedData.sql
      - store_artifacts:
          path: functional_tests/reports
          destination: reports

  approve_to_deploy:
    docker:
      - image: circleci/node:13.4
    steps:
      - run: echo "Hold for approval"

  # build_ui_push_to_s3:
  #   parameters:
  #     env_name:
  #       type: string
  #     distributionId:
  #       type: string
  #   executor:
  #     name: node/default
  #   steps:
  #     - *fast-checkout
  #     - node/install-packages
  #     - run: npm run gulp -- -- --env=<< parameters.env_name >>
  #     - aws-s3/sync:
  #         arguments: |
  #           --cache-control "max-age=8387800" \
  #           --exclude "*" \
  #           --include "*.svg" \
  #           --include "*.jpeg"
  #         from: crowdsource-ui/target/
  #         to: "s3://${STATIC_CONTENT_BUCKET}-<< parameters.env_name >>"
  #     - aws-s3/sync:
  #         arguments: |
  #           --cache-control "max-age=0, s-maxage=600" \
  #           --exclude "*.svg" \
  #           --exclude "*.jpeg"
  #         from: crowdsource-ui/target/
  #         to: "s3://${STATIC_CONTENT_BUCKET}-<< parameters.env_name >>"
  #     - run: aws cloudfront create-invalidation --distribution-id << parameters.distributionId >> --paths '/*'

  build_ui_push_to_blob_storage:
    parameters:
      env_name:
        type: string
    docker:
      - image: circleci/node:13.4
    steps:
      - *fast-checkout
      - node/install-packages
      - run:
          name: build_ui
          command: |
            # npm run gulp -- -- --env=<< parameters.env_name >>
            sudo apt-get update -y
            sudo apt-get install -y apt-utils
            sudo apt-get install wget
            sudo apt install -y keyutils

            keyctl session

            mkdir /usr/src/app/utils/
            wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux 
            tar -xf azcopy_v10.tar.gz --strip-components=1
            cp azcopy /usr/src/app/utils/
            /usr/src/app/utils/azcopy login --tenant-id ${TENANT_ID} --service-principal --application-id ${APP_ID}

            /usr/src/app/utils/azcopy copy "crowdsource-ui/target/" "${AZURE_ACC_URL}/${AZURE_STATIC_CONTENT}-<< parameters.env_name >>/" --recursive

  db_migrate_azure:
    parameters:
      db_name:
        type: string
    executor:
      name: node/default
    steps:
      - *fast-checkout
      - run:
          name: Run DB Migrate
          command: |
            echo << parameters.db_name >>
            export DATABASE_URL=postgresql://${AZURE_DB_USER}:${AZURE_DB_PASS}@${AZURE_DB_HOST}/<< parameters.db_name >>
            echo << parameters.db_name >>
            echo $DATABASE_URL
            npm run install:api
            cd crowdsource-api && npx db-migrate up

  aks_deployment:
    executor: azure-aks/default
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      env-name:
        description: |
          Name of the env
        type: string

    steps:
      - *fast-checkout
      - aws-cli/setup:
          profile-name: circle-ci
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          perform-login: true
          resource-group: ${AZURE_RESOURCE_GROUP}
      - run:
          command: |
            ENV_IMAGE_NAME=${AZURE_LOGIN_SERVER_NAME}/${AZURE_REPO}:<< parameters.env-name >>

            ENV_IMAGE_NAME_DB_REFRESHER=${AZURE_LOGIN_SERVER_NAME}/${DB_REFRESHER_REPO}:<< parameters.env-name >>
            # kubectl -n << parameters.env-name >> apply  -f ${HOME}/project/crowdsource-api/k8s-deployments/autoscaler_<< parameters.env-name >>.yaml

            sed -e "s|IMAGE_NAME|$ENV_IMAGE_NAME|g;s/CIRCLE_SHA1/$CIRCLE_SHA1/g" ${HOME}/project/crowdsource-api/k8s-deployments/azure/deployment.yaml | kubectl -n << parameters.env-name >> apply  -f -
            sed -e "s|IMAGE_NAME_DB_REFRESHER|$ENV_IMAGE_NAME_DB_REFRESHER|g;s/CIRCLE_SHA1/$CIRCLE_SHA1/g" ${HOME}/project/db-refresher/k8s-deployments/dbrefresher.yaml | kubectl -n << parameters.env-name >> apply  -f -
          name: Deploy container

workflows:
  build_test_deploy:
    jobs:
      - node/test:
          version: "14.15"

      - create-workspace:
          name: create-workspace
          requires:
            - node/test
          filters:
            branches:
              only: azure

      - db_migrate_azure:
          name: migrate_dev_azure
          db_name: ${AZURE_DEV_DB_NAME}
          requires:
            - create-workspace

      - build_ui_push_to_blob_storage:
          name: build_dev_ui
          env_name: dev
          requires:
            - migrate_dev_azure

      - azure-acr/build-and-push-image:
          name: push_dev_image
          login-server-name: ${AZURE_LOGIN_SERVER_NAME}
          registry-name: ${AZURE_REGISTRY}
          path: ./crowdsource-api
          extra-build-args: --build-arg NODE_ENV=dev
          repo: ${AZURE_REPO}
          tag: dev
          requires:
            - migrate_dev_azure

      - azure-acr/build-and-push-image:
          name: push_dev_db_refresher_image
          login-server-name: ${AZURE_LOGIN_SERVER_NAME}
          registry-name: ${AZURE_REGISTRY}
          dockerfile: Dockerfile-dbRefresh
          path: ./db-refresher
          extra-build-args: --build-arg NODE_ENV=dev
          repo: ${DB_REFRESHER_REPO}
          tag: dev
          requires:
            - migrate_dev_azure

      - aks_deployment:
          name: dev_deployment_eks
          cluster-name: ${AZURE_CLUSTER_NAME}
          env-name: dev
          requires:
            - push_dev_image
            - push_dev_db_refresher_image
      # - aws-ecr/build-and-push-image:
      #     name: push_dev_image
      #     repo: ${REPO}
      #     tag: dev
      #     path: ./crowdsource-api
      #     extra-build-args: --build-arg NODE_ENV=dev
      #     requires:
      #       - migrate_dev_aws
      # - aws-ecr/build-and-push-image:
      #     name: push_dev_db_refresher_image
      #     repo: ${DB_REFRESHER_REPO}
      #     dockerfile: Dockerfile-dbRefresh
      #     path: ./db-refresher
      #     tag: "dev,test,prod,uat,cug"
      #     requires:
      #       - migrate_dev_aws
      # - run_functional_tests:
      #     name: functional_tests_dev
      #     env_name: dev
      #     db_name: ${DEV_DB_NAME}
      #     requires:
      #       - dev_deployment_eks
      #       - build_dev_ui
      # - approve_to_deploy:
      #     name: approve_cug_deployment_eks
      #     type: approval
      #     requires:
      #       - dev_deployment_eks
      #       - build_dev_ui
      #       # - functional_tests_dev
      #     filters:
      #       branches:
      #         only: master
      # - db_migrate_aws:
      #     name: migrate_cug_aws
      #     db_name: ${CUG_DB_NAME}
      #     requires:
      #       - approve_cug_deployment_eks
      # - aws-ecr/build-and-push-image:
      #     name: push_cug_image
      #     repo: ${REPO}
      #     tag: cug
      #     path: ./crowdsource-api
      #     extra-build-args: --build-arg NODE_ENV=cug
      #     requires:
      #       - migrate_cug_aws
      # - build_ui_push_to_s3:
      #     name: build_cug_ui
      #     env_name: cug
      #     distributionId: ${CUG_DISTRIBUTION_ID}
      #     requires:
      #       - push_cug_image
      # - eks_fargate_deployment:
      #     name: cug_deployment_eks
      #     cluster-name: ${CLUSTER_NAME}
      #     env-name: cug
      #     requires:
      #       - push_cug_image
      # - approve_to_deploy:
      #     name: approve_test_deployment_eks
      #     type: approval
      #     requires:
      #       - dev_deployment_eks
      #       - build_dev_ui
      #       # - functional_tests_dev
      #     filters:
      #       branches:
      #         only: master
      # - db_migrate_aws:
      #     name: migrate_test_aws
      #     db_name: ${TEST_DB_NAME}
      #     requires:
      #       - approve_test_deployment_eks
      # - aws-ecr/build-and-push-image:
      #     name: push_test_image
      #     repo: ${REPO}
      #     tag: test
      #     path: ./crowdsource-api
      #     extra-build-args: --build-arg NODE_ENV=test
      #     requires:
      #       - migrate_test_aws
      # - build_ui_push_to_s3:
      #     name: build_test_ui
      #     env_name: test
      #     distributionId: ${TEST_DISTRIBUTION_ID}
      #     requires:
      #       - push_test_image
      # - eks_fargate_deployment:
      #     name: test_deployment_eks
      #     cluster-name: ${CLUSTER_NAME}
      #     env-name: test
      #     requires:
      #       - push_test_image
      # - run_functional_tests:
      #     name: functional_tests_test
      #     env_name: test
      #     db_name: ${TEST_DB_NAME}
      #     requires:
      #       - test_deployment_eks
      #       - build_test_ui
      # - approve_to_deploy:
      #     name: approve_uat_deployment_eks
      #     type: approval
      #     requires:
      #       - test_deployment_eks
      #       - build_test_ui
      #       # - functional_tests_dev
      # - db_migrate_aws:
      #     name: migrate_uat_aws
      #     db_name: ${UAT_DB_NAME}
      #     requires:
      #       # - functional_tests_test
      #       - approve_uat_deployment_eks
      # - aws-ecr/build-and-push-image:
      #     name: push_uat_image
      #     repo: ${REPO}
      #     tag: uat
      #     path: ./crowdsource-api
      #     extra-build-args: --build-arg NODE_ENV=uat
      #     requires:
      #       - migrate_uat_aws
      # - build_ui_push_to_s3:
      #     name: build_uat_ui
      #     env_name: uat
      #     distributionId: ${UAT_DISTRIBUTION_ID}
      #     requires:
      #       - push_uat_image
      # - eks_fargate_deployment:
      #     name: uat_deployment_eks
      #     cluster-name: ${CLUSTER_NAME}
      #     env-name: uat
      #     requires:
      #       - push_uat_image
      # - approve_to_deploy:
      #     name: approve_prod_deployment_eks
      #     type: approval
      #     requires:
      #       - test_deployment_eks
      #       - build_test_ui
      #       # - functional_tests_test
      #       - uat_deployment_eks
      # - db_migrate_aws:
      #     name: migrate_prod_aws
      #     db_name: ${DB_NAME}
      #     requires:
      #       - approve_prod_deployment_eks
      # - build_ui_push_to_s3:
      #     name: build_prod_ui
      #     env_name: prod
      #     distributionId: ${PROD_DISTRIBUTION_ID}
      #     requires:
      #       - push_prod_image
      # - aws-ecr/build-and-push-image:
      #     name: push_prod_image
      #     repo: ${REPO}
      #     tag: prod
      #     path: ./crowdsource-api
      #     extra-build-args: --build-arg NODE_ENV=prod
      #     requires:
      #       - migrate_prod_aws
      # - eks_fargate_deployment:
      #     name: prod_deployment_eks
      #     cluster-name: ${CLUSTER_NAME}
      #     env-name: prod
      #     requires:
      #       - push_prod_image
