version: 2
jobs:
    build:
        docker:
            - image: circleci/node:13.4
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
            
            - run:
                name: Deploy in test env
                command: |
                  wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-265.0.0-linux-x86_64.tar.gz
                  tar -zxf google-cloud-sdk-*
                  cd google-cloud-sdk
                  pwd
                  ./install.sh --quiet
                  echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
                  gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
                  gcloud --quiet config set project ${GCP_PROJECT}
                  cd ~/crowdsource-dataplatform
                  gcloud app deploy app.yaml

                  rm ${HOME}/gcp-key.json