version: 2.1
jobs:
  build:
    docker:
      — image: circleci/node:13.4
    working_directory: ~/crowdsource-dataplatform
    steps:
      — checkout
      - run: 
        command: npm install
      — run: 
        command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build