version: 2.1
orbs:
  node: circleci/node@4.4.0
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-eks: circleci/aws-eks@1.0.3
  aws-cli: circleci/aws-cli@1.4.0
  kubernetes: circleci/kubernetes@0.11.2
  aws-s3: circleci/aws-s3@2.0.0

definition:
  fast-checkout: &fast-checkout
    attach_workspace:
      at: .

jobs:
  create-workspace:
    executor: node/default
    steps:
      - checkout
      - run: rm -rf .git
      - persist_to_workspace:
          root: .
          paths:
            - .

  run_functional_tests:
    parameters:
      env_name:
        type: string
      db_name:
        type: string
    executor:
      name: node/default
    steps:
      - *fast-checkout
      - run:
          name: Gauge tests
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client git-all gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libgbm-dev libappindicator1 libnss3 lsb-release xdg-utils wget
            psql "postgresql://${DEV_DB_USER}:${DB_PASS_AWS}@${DB_HOST_AWS}/<< parameters.db_name >>" -f functional_tests/sql/dataSeed.sql
            sudo rm -rf /var/lib/apt/lists/*
            npm run install:ft
            npm run functional_test -- -- --env <<parameters.env_name>>
            psql "postgresql://${DEV_DB_USER}:${DB_PASS_AWS}@${DB_HOST_AWS}/<< parameters.db_name >>" -f functional_tests/sql/deleteSeedData.sql
      - store_artifacts:
          path: functional_tests/reports
          destination: reports

  approve_to_deploy:
    docker:
      - image: circleci/node:13.4
    steps:
      - run: echo "Hold for approval"

  build_ui_push_to_s3:
    parameters:
      env_name:
        type: string
      distributionId:
        type: string
    executor:
      name: node/default
    steps:
      - *fast-checkout
      - node/install-packages
      - run: npm run gulp -- -- --env=<< parameters.env_name >>
      - aws-s3/sync:
          arguments: |
            --cache-control "max-age=8387800" \
            --exclude "*" \
            --include "*.svg" \
            --include "*.jpeg"
          from: crowdsource-ui/target/
          to: "s3://${STATIC_CONTENT_BUCKET}-<< parameters.env_name >>"
      - aws-s3/sync:
          arguments: |
            --cache-control "max-age=0, s-maxage=600" \
            --exclude "*.svg" \
            --exclude "*.jpeg"
          from: crowdsource-ui/target/
          to: "s3://${STATIC_CONTENT_BUCKET}-<< parameters.env_name >>"
      - run: aws cloudfront create-invalidation --distribution-id << parameters.distributionId >> --paths '/*'

  db_migrate_aws:
    parameters:
      db_name:
        type: string
    executor:
      name: node/default
    steps:
      - *fast-checkout
      - run:
          name: Run DB Migrate
          command: |
            echo << parameters.db_name >>
            export DATABASE_URL=postgresql://${DEV_DB_USER}:${DB_PASS_AWS}@${DB_HOST_AWS}/<< parameters.db_name >>
            echo << parameters.db_name >>
            echo $DATABASE_URL
            npm run install:api
            cd crowdsource-api && npx db-migrate up

  eks_fargate_deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      env-name:
        description: |
          Name of the env
        type: string

    steps:
      - *fast-checkout
      - aws-cli/setup:
          profile-name: circle-ci
      - kubernetes/install
      - run:
          command: |
            aws eks --region ap-south-1 update-kubeconfig --name << parameters.cluster-name >>
            ENV_IMAGE_NAME=${AWS_ECR_ACCOUNT_URL}/${REPO}:<< parameters.env-name >>
            ENV_IMAGE_NAME_DB_REFRESHER=${AWS_ECR_ACCOUNT_URL}/${DB_REFRESHER_REPO}:<< parameters.env-name >>
            kubectl -n << parameters.env-name >> apply  -f ${HOME}/project/crowdsource-api/k8s-deployments/autoscaler_<< parameters.env-name >>.yaml
            sed -e "s|IMAGE_NAME|$ENV_IMAGE_NAME|g;s/CIRCLE_SHA1/$CIRCLE_SHA1/g" ${HOME}/project/crowdsource-api/k8s-deployments/deployment.yaml | kubectl -n << parameters.env-name >> apply  -f -
            sed -e "s|IMAGE_NAME_DB_REFRESHER|$ENV_IMAGE_NAME_DB_REFRESHER|g;s/CIRCLE_SHA1/$CIRCLE_SHA1/g" ${HOME}/project/db-refresher/k8s-deployments/dbrefresher.yaml | kubectl -n << parameters.env-name >> apply  -f -
          name: Deploy container

workflows:
  build_test_deploy:
    jobs:
      - node/test:
          version: "14.15"

      - create-workspace:
          name: create-workspace
          requires:
            - node/test
          filters:
            branches:
              only: [AWS]

      - aws-ecr/build-and-push-image:
          name: push_cug_image
          repo: ${REPO}
          tag: cug
          path: ./crowdsource-api
          extra-build-args: --build-arg NODE_ENV=cug
          requires:
            - create-workspace

      - aws-ecr/build-and-push-image:
          name: push_db_refresher_image
          repo: ${DB_REFRESHER_REPO}
          dockerfile: Dockerfile-dbRefresh
          path: ./db-refresher
          tag: "cug"
          requires:
            - create-workspace

      - db_migrate_aws:
          name: migrate_cug_aws
          db_name: ${CUG_DB_NAME}
          requires:
            - push_db_refresher_image
            - push_cug_image

      - aws-ecr/build-and-push-image:
          name: push_cug_image
          repo: ${REPO}
          tag: cug
          path: ./crowdsource-api
          extra-build-args: --build-arg NODE_ENV=cug
          requires:
            - migrate_cug_aws

      - build_ui_push_to_s3:
          name: build_cug_ui
          env_name: cug
          distributionId: ${CUG_DISTRIBUTION_ID}
          requires:
            - push_cug_image

      - eks_fargate_deployment:
          name: cug_deployment_eks
          cluster-name: ${CLUSTER_NAME}
          env-name: cug
          requires:
            - push_cug_image
