apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: vakyansh-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vakyansh
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60


status:
  observedGeneration: 1
  lastScaleTime: 10
  currentReplicas: 2
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0