const selectors = taiko => {
    return {
      languageDropdown: taiko.dropDown({ id: 'languageDropDown' }),
      asrLink: taiko.button('TTS Initiative', taiko.below(taiko.dropDown({ id: 'languageDropDown' }))),
      asrActiveLink: taiko.button('TTS Initiative', { class: 'active' }),
      textLink: taiko.button('ASR Initiative', taiko.below(taiko.dropDown({ id: 'languageDropDown' }))),
      parallelLink: taiko.button('Translation Initiative', taiko.below(taiko.dropDown({ id: 'languageDropDown' }))),
      ocrLink: taiko.button('OCR Initiative', taiko.below(taiko.dropDown({ id: 'languageDropDown' }))),
      bronzeMedalImage: taiko.image('Medal', taiko.above('Bronze')),
      silverMedalImage: taiko.image('Medal', taiko.above('Silver')),
      goldMedalImage: taiko.image('Medal', taiko.above('Gold')),
      platinumMedalImage: taiko.image('Medal', taiko.above('Platinum')),
      contributionRadioButton: taiko.radioButton({ id: 'action1' }),
      validationRadioButton: taiko.radioButton({ id: 'action2' }),
      userOptionButton: taiko.button({ id: 'userOptions' }),
      myBadgesText: taiko.text('My Badges'),
      yourMedalGalleryText: taiko.text('Your Medal Gallery'),
      badgeInstruction: taiko.text('Please keep contributing actively to stand a chance to get recognised.'),
      badgeInstruction2: taiko.text('Levels and badges may take upto 48 hours to update.'),
      ocrInitiativeTab: taiko.button('OCR Initiative'),
      translationInitiativeTab: taiko.button('Translation Initiative'),
      ttsInitiativeTab: taiko.button('TTS Initiative'),
      odiaText: taiko.text('Odia'),
      homeText: taiko.text('Home'),
      brandContributorText: taiko.text('Contribute and become a Brand Contributor'),
      odiaOcrBronzeValidateBadge: taiko.$(`//div[@data-testid="or-ocr-bronze-validate-medal"]`),
      odiaOcrSilverValidateBadge: taiko.$(`//div[@data-testid="or-ocr-silver-validate-medal"]`),
      odiaOcrGoldValidateBadge: taiko.$(`//div[@data-testid="or-ocr-gold-validate-medal"]`),
      asOcrBronzeContributeBadge: taiko.$(`//div[@data-testid="as-ocr-bronze-contribute-medal"]`),
      asOcrSilverContributeBadge: taiko.$(`//div[@data-testid="as-ocr-silver-contribute-medal"]`),
      badgeClickablePopup: taiko.$(`//div[contains(@class, 'Medal_zoom')]`),
      bnTranslationBronzeValidateBadge: taiko.$(`//div[@data-testid="bn-translation-bronze-validate-medal"]`),
      bnTranslationSilverValidateBadge: taiko.$(`//div[@data-testid="bn-translation-silver-validate-medal"]`),
      bnTranslationGoldValidateBadge: taiko.$(`//div[@data-testid="bn-translation-gold-validate-medal"]`),
      bnTranslationPlatinumValidateBadge: taiko.$(`//div[@data-testid="bn-translation-platinum-validate-medal"]`),
      medalPlaceholder: taiko.$(`//div[contains(@class, 'MedalPlaceholder')]`),
      noBadgeEarnedText: taiko.text('No badge earned for TTS Initiative'),

      playIcon: taiko.image('Play Icon'),
      pauseIcon: taiko.image('Pause Icon'),
      replayIcon: taiko.image('Replay Icon'),
      breadCrumb: taiko.image('ttsLogo'),
      ttsInitiativeHeading: taiko.text('Enrich your language by typing the audio that you hear'),
      transcribeText: taiko.text('Transcribe'),
      validateText: taiko.text('Validate'),
      closeButton: taiko.button('Close'),
      contributionTrackerText: taiko.text('Contribution Tracker'),
      overAllSummaryText: taiko.text('Overall Summary'),
      ttsInitiativeContributionHeading1: taiko.text('Contributions made to TTS Initiative'),
      top3contributionText: taiko.text('Your language and top 3 contributed languages'),
      userNameField: taiko.textBox({ id: 'userName' }),
      viewAllDetails: taiko.link({ 'data-testid': 'ViewAllDetailButton' }),
      testSpeakerIcon: taiko.button({ 'data-testid': 'testYourSpeaker_button' }),
      languageText: taiko.text('Languages'),
      peopleParticipatedText: taiko.text('People participated'),
      durationTranscribedText: taiko.text('Duration transcribed'),
      durationValidatedText: taiko.text('Duration validated'),
      submitButton: taiko.button('Submit'),
      cancelButton: taiko.button('Cancel'),
      skipButton: taiko.button('Skip'),
      youContributedText: taiko.text('You contributed'),
      button: taiko.button({ 'data-testid': 'Button' }),
      contributeCardText: taiko.text('Please make your own language AI models better by validating data'),
      validateCardText: taiko.text('Only contributions invited for the selected language'),
      changeUserText: taiko.text('Change User'),
      userDetailsText: taiko.text('User Details'),
      asrValidateThankYouPageText1: taiko.text('TTS Initiative Target Achieved'),
      asrValidateThankYouPageText2: taiko.text('Transcription (in sentences)'),
      asrValidateThankYouPageText3: taiko.text('Hour(s)'),
      translateText: taiko.text('Translate'),
      translationInitiativeContributionHeading1: taiko.text('Contributions made to Translation Initiative'),
      translationInitiativeContributionHeading2: taiko.text('Your language pair and top 3 contributed language pairs'),
      translationInitiativeHeading: taiko.text('Enrich your language by translating text'),
      translationDoneText: taiko.text('Translations done'),
      translationValidatedText: taiko.text('Translations validated'),
      userDetailsCloseButton: taiko.button({ class: 'btn-close' }),
      languagePairText: taiko.text('Language pairs'),
      translationBreadcrumb: taiko.image('translationLogo'),
      shareOnText: taiko.text('Share on'),
      knowMore: taiko.link('Know More'),
      validateThankYouPageText: taiko.text('Validate 5 sentence(s) to earn your Bronze Badge.'),
      contributeToYourLanguageText: taiko.text('Contribute to your language!'),
      parallelOrTargetAchievedText: taiko.text('Odia Translation Initiative Target Achieved'),
      parallelValidateThankYouPageText1: taiko.text('Validation (in sentences)'),

      ocrInitiativeHeading: taiko.text('Enrich your language by typing the text you see'),
      labelText: taiko.text('Label'),
      ocrInitiativeContributionHeading: taiko.text('Contributions made to OCR Initiative'),
      imageLabelledText: taiko.text('Images labelled'),
      imageValidatedText: taiko.text('Images validated '),
      ocrBreadcrumb: taiko.image('ocrLogo'),
      contributeMoreText: taiko.button('Contribute More'),
      ocrThankYouEnthusiamText: taiko.text('Thank you for your enthusiasm to label the images'),
      translationThankYouEnthusiamText: taiko.text('Thank you for your enthusiasm to translate the sentences.'),
      ttsThankYouEnthusiamText: taiko.text('Thank you for your enthusiasm to transcribe the recordings.'),
      validateMoreText: taiko.button('Validate More'),
      ocrValidateThankYouEnthusiamText: taiko.text(
        'Thank you for your enthusiasm to validate the image labels.'
      ),
      translationValidateThankYouEnthusiamText: taiko.text(
        'Thank you for your enthusiasm to validate the translations.'
      ),
      ttsValidateThankYouEnthusiamText: taiko.text(
        'Thank you for your enthusiasm to validate the recordings.'
      ),
      badgeWinText: taiko.text('Congratulations on winning a new badge!'),
      ocrBronzeBadgeWinText: taiko.text('You’ve earned your OCR Initiative Bronze Brand Contributor Badge'),
      ocrKnValidateImageLabelTexts: taiko.text('Validated 5 image label(s) in Kannada'),
      downloadText: taiko.text('Download'),
      enBronzeBadgeImage: taiko.image('Bronze Badge english'),
      bronzeBadgeImage: taiko.image('Bronze badge'),
      bronzeBadgeDownload: taiko.image('bronzeDownload'),
      installNow: taiko.link('Install Now'),
      watchVideo: taiko.button('Watch the video'),
      targetProgress: taiko.$('//*[@data-testid="TargetProgress"]'),
      ocrValidateThankYouPageText1: taiko.text('OCR Initiative Target Achieved'),
      ocrValidateThankYouPageText2: taiko.text('Image(s)'),
      ocrValidateThankYouPageText3: taiko.text('Labelled (in images)'),
      yourBagdeText: taiko.text('Your Badge'),
      bronzeValidatorText: taiko.text('You are a Bronze Validator'),
      startParticipatingText: taiko.link('Start Participating'),
      asrInitiativeHeading: taiko.text('Enrich your language by donating your voice'),
      languageIconImage: taiko.image('Language Icon'),
      userNameErrorMsg: taiko.text(`Please don't use only numerics or email as username`),
      motherTongue: taiko.dropDown({ id: 'motherTongue' }),
      age: taiko.dropDown({ id: 'age' }),
      others: taiko.radioButton({ id: 'others' }),
      female: taiko.radioButton({ id: 'female' }),
      male: taiko.radioButton({ id: 'male' }),
      doneButton: taiko.button('Done'),
      quickTipsText: taiko.text('Quick Tips'),
      closeTipsButton: taiko.image({ alt: 'Close' }),
      contributeIcon: taiko.image('Contribute Icon'),
      validateIcon: taiko.image('Validate Icon'),
      durationRecordedText: taiko.text('Duration recorded'),
      youValidatedText: taiko.text('You validated'),
      selectLanguageDropDown: taiko.dropDown({ 'data-testid': 'SelectContributionLanguage' }),
      transgenderMale: taiko.radioButton({ id: 'transgenderMale' }),
      transgenderFemale: taiko.radioButton({ id: 'transgenderFemale' }),
      ratherNotSay: taiko.radioButton({ id: 'ratherNotSayGender' }),
      feedbackIconImage: taiko.image({ alt: 'Feedback Icon' }),
      closeImage: taiko.image('Close'),
      iconImage: taiko.image({ alt: 'icon' }),
      revisit1: taiko.radioButton({ id: 'revisit1' }),
      revisit2: taiko.radioButton({ id: 'revisit2' }),
      revisit3: taiko.radioButton({ id: 'revisit3' }),
      noCheckbox: taiko.radioButton({ id: 'feedbackFormNoCheckbox' }),
      mayBeCheckbox: taiko.radioButton({ id: 'feedbackFormMaybeCheckbox' }),
      yesCheckbox: taiko.radioButton({ id: 'feedbackFormYesCheckbox' }),
      feedbackThankYouText: taiko.text('Thank you for your feedback!'),
      submitSuccessfulText: taiko.text('Submitted successfully'),
      asrInitiativeText: taiko.text('ASR Initiative'),
      reportText: taiko.text('Report'),
      reportButton: taiko.button({ id: 'report' }),
      reportContentText: taiko.text('Report Content'),
      charLimitText: taiko.text('Only 1000 characters allowed'),
      othersCheckbox: taiko.radioButton({ id: 'reportFormCheckboxOthers' }),
      misinformationCheckbox: taiko.radioButton({ id: 'reportFormCheckboxMisinformation' }),
      politicalStatementCheckbox: taiko.radioButton({ id: 'reportFormCheckboxPolitical Statement' }),
      prohibitedContentCheckbox: taiko.radioButton({ id: 'reportFormCheckboxProhibited Content' }),
      offensiveCheckbox: taiko.radioButton({ id: 'reportFormCheckboxOffensive' }),
      thankYouText: taiko.text('Thank You'),
      asrProgressBarText: taiko.text('ASR Initiative Target Achieved'),
      recordingText: taiko.text('Recordings (in hours)'),
      hourText: taiko.text('Hour(s)'),
      contribute5RecordingText: taiko.text('Contribute 5 recording(s) to earn your Bronze Badge.'),
      termsAndConditionsText: taiko.text('Terms and Conditions'),
      backButton: taiko.button({ id: 'back-btn' }),
      asrContributionMadeText: taiko.text('Contributions made to ASR Initiative'),
      speakText: taiko.text('Speak'),
      feedbackText: taiko.text('We would like to get your feedback to improve this platform'),
      opinionText: taiko.text('What is your opinion of this page'),
      feedbackCategoryText: taiko.text('Please select your feedback category'),
      shareFeedbackText: taiko.text('Share your feedback below:'),
      recommendText: taiko.text('Would you recommend Crowdsourcing to your friends & family?'),
      revisitText: taiko.text('Would you revisit Crowdsourcing?'),
      startRecordingButton : taiko.button('Start Recording'),
      languageDropdownDashboard: taiko.dropDown({ id: 'language' }),
      tipsButton: taiko.button('Tips')
    };
  };

  const getSelectors = async taiko => {
    return selectors(taiko);
  };

  module.exports = getSelectors;